id: P60D68FB7
initial_creation_type: ocr
source_metadata:
  volumes:
    84ecc549fd514e70892dda86068bb57e:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡེ་ཤེས་སྙིང་པོ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1605
      volume_number: 57
